### ISSUE TITLE
Write up about the transfer

### ISSUE THREAD

**Issue by gap736uk** [cedadev/cedadocs_migrate#15]
Here's some starting text I have just blasted into an email to EPrints about why we are transferring:

Our EPrints repository was originally setup as part of the OJIMS project ( http://www.ariadne.ac.uk/issue/61/callaghan-et-al/ ) to act as a grey literature repository to complement our data archive (then the British Atmospheric Data Centre, now the Centre for Environmental Data Analysis archive). The intent of that original service was to provide a service that was unavailable at the time, providing a well-structured service both for CEDA staff to make their own outputs such as presentations and reports available but primarily to act as a repository for a range of items that related to the CEDA data archive holdings (e.g. research aircraft flight logs, calibration details, dataet user-guides etc).

Over time we’ve migrated the service from server to server and tried to maintain the EPrints service with updates as required.
 
However, during this time period alternative, freely available services have come along such as Zenodo which provide much the same functionality – and in some cases better – than our own document repository. Crucially, for us, these come with no additional overheads for our staff to maintain the service itself as we presently have with running an EPrints service. This was highlighted to us in an incident that hit our service 2 years ago where we suffered from a service issue which required the service to come offline for sometime whilst it was updated.
 
Given that Zenodo community provides the scope that we desire and is an easy to use interface with no additional service overheads for us we decided to transfer our content to Zenodo. It also offers some aspects that we haven’t implemented locally … though we do know that we could do this – e.g. DOI minting, orcids… that said, this also highlights that our use of EPrints doesn’t _quite_ align with it’s intended use.. e.g. we can mint DOIs as part of our NERC data centre work, but we’re doing this as part of our dataset curation work as opposed to grey literature items and there is a defined scope of the DOIs that we’re using there that doesn’t work for us in the EPrints case, meanwhile Zenodo does the DOIs (and versioning!) well.

Additionally, EPrints is PERL based and we only have one person here who has PERL experience – we’re mainly Python based – and the API interface for Zenodo means that we can actually use it programmatically regardless of our own programming language skill set.

It isn’t an exact match and our migration does mean we’re having to coax the metadata into various Zenodo fields, but we’re happy with the resulting records that we’ll get.

**Comment by Adik8688** [comment]
https://techblog.ceda.ac.uk/2023/05/25/cedadocs-transfer.html
